In [53]:
import numpy as np
import pandas as pd
import matplotlib as mlt

In [5]:
import numpy
numpy.version.version
#checking the version

'1.23.5'

In [6]:
a = np.array([1,3,5])
a
print(a)
a.shape

[1 3 5]


(3,)

In [7]:
a.dtype

dtype('int32')

In [15]:
b= np.array([[1.2, 3.5, 5.1], [2.6, 5.9, 2.1]])
print(b)
b.shape
#2d array

[[1.2 3.5 5.1]
 [2.6 5.9 2.1]]


(2, 3)

In [17]:
b.dtype

dtype('float64')

In [21]:
c= np.array([[[1.2, 3.5, 5.1], [2.6, 5.9, 2.1], [1.6, 4, 6.8]]])
print(c)
c.shape
#3d array

[[[1.2 3.5 5.1]
  [2.6 5.9 2.1]
  [1.6 4.  6.8]]]


(1, 3, 3)

In [37]:
a= np.array([[1, 3], [6, 5]])
b= np.array([[4, 5], [2, 9]])
print(a)
print(b)

c = (a*b)
print(c)

c.shape

[[1 3]
 [6 5]]
[[4 5]
 [2 9]]
[[ 4 15]
 [12 45]]


(2, 2)

In [59]:
col_names = ['preganant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'diabetic']
pima = pd.read_csv('C:/Users/acer/DataMiningLab/Datasets/pima_dataset.csv', header=None, names=col_names)
pima.head(20)

preganant  glucose  bp  skin  insulin   bmi  pedigree  age  diabetic
0           6      148  72    35        0  33.6     0.627   50         1
1           1       85  66    29        0  26.6     0.351   31         0
2           8      183  64     0        0  23.3     0.672   32         1
3           1       89  66    23       94  28.1     0.167   21         0
4           0      137  40    35      168  43.1     2.288   33         1
5           5      116  74     0        0  25.6     0.201   30         0
6           3       78  50    32       88  31.0     0.248   26         1
7          10      115   0     0        0  35.3     0.134   29         0
8           2      197  70    45      543  30.5     0.158   53         1
9           8      125  96     0        0   0.0     0.232   54         1
10          4      110  92     0        0  37.6     0.191   30         0
11         10      168  74     0        0  38.0     0.537   34         1
12         10      139  80     0        0  27.1     1.441   57         0
13          1      189  60    23      846  30.1     0.398   59         1
14          5      166  72    19      175  25.8     0.587   51         1
15          7      100   0     0        0  30.0     0.484   32         1
16          0      118  84    47      230  45.8     0.551   31         1
17          7      107  74     0        0  29.6     0.254   31         1
18          1      103  30    38       83  43.3     0.183   33         0
19          1      115  70    30       96  34.6     0.529   32         1

In [55]:
pima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   preganant  768 non-null    int64  
 1   glucose    768 non-null    int64  
 2   bp         768 non-null    int64  
 3   skin       768 non-null    int64  
 4   insulin    768 non-null    int64  
 5   bmi        768 non-null    float64
 6   pedigree   768 non-null    float64
 7   age        768 non-null    int64  
 8   diabetic   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [56]:
pima.describe()

preganant     glucose          bp        skin     insulin         bmi  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

         pedigree         age    diabetic  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [57]:
pima.index

RangeIndex(start=0, stop=768, step=1)

In [58]:
pima.shape

(768, 9)

In [60]:
pima.groupby('diabetic').size()

diabetic
0    500
1    268
dtype: int64

In [61]:
pima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   preganant  768 non-null    int64  
 1   glucose    768 non-null    int64  
 2   bp         768 non-null    int64  
 3   skin       768 non-null    int64  
 4   insulin    768 non-null    int64  
 5   bmi        768 non-null    float64
 6   pedigree   768 non-null    float64
 7   age        768 non-null    int64  
 8   diabetic   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [63]:
pima.describe()

preganant     glucose          bp        skin     insulin         bmi  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

         pedigree         age    diabetic  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [65]:
pima.columns

Index(['preganant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree',
       'age', 'diabetic'],
      dtype='object')

In [66]:
pima.shape

(768, 9)

In [67]:
pima.groupby('diabetic').size()

diabetic
0    500
1    268
dtype: int64

In [69]:
pima.describe().T

count        mean         std     min       25%       50%  \
preganant  768.0    3.845052    3.369578   0.000   1.00000    3.0000   
glucose    768.0  120.894531   31.972618   0.000  99.00000  117.0000   
bp         768.0   69.105469   19.355807   0.000  62.00000   72.0000   
skin       768.0   20.536458   15.952218   0.000   0.00000   23.0000   
insulin    768.0   79.799479  115.244002   0.000   0.00000   30.5000   
bmi        768.0   31.992578    7.884160   0.000  27.30000   32.0000   
pedigree   768.0    0.471876    0.331329   0.078   0.24375    0.3725   
age        768.0   33.240885   11.760232  21.000  24.00000   29.0000   
diabetic   768.0    0.348958    0.476951   0.000   0.00000    0.0000   

                 75%     max  
preganant    6.00000   17.00  
glucose    140.25000  199.00  
bp          80.00000  122.00  
skin        32.00000   99.00  
insulin    127.25000  846.00  
bmi         36.60000   67.10  
pedigree     0.62625    2.42  
age         41.00000   81.00  
diabetic     1.00000    1.00

In [70]:
#Handling of missing values

pima_new = pima.copy(deep = True)
pima_new[['glucose', 'bp', 'skin', 'insulin', 'bmi']] = pima_new[['glucose', 'bp', 'skin', 'insulin', 'bmi']].replace(0,np.NaN)
print("below table shows we marked the deature value from...")
print(pima_new.isnull().sum())

below table shows we marked the deature value from...
preganant      0
glucose        5
bp            35
skin         227
insulin      374
bmi           11
pedigree       0
age            0
diabetic       0
dtype: int64


In [71]:
pima_new

preganant  glucose    bp  skin  insulin   bmi  pedigree  age  diabetic
0            6    148.0  72.0  35.0      NaN  33.6     0.627   50         1
1            1     85.0  66.0  29.0      NaN  26.6     0.351   31         0
2            8    183.0  64.0   NaN      NaN  23.3     0.672   32         1
3            1     89.0  66.0  23.0     94.0  28.1     0.167   21         0
4            0    137.0  40.0  35.0    168.0  43.1     2.288   33         1
..         ...      ...   ...   ...      ...   ...       ...  ...       ...
763         10    101.0  76.0  48.0    180.0  32.9     0.171   63         0
764          2    122.0  70.0  27.0      NaN  36.8     0.340   27         0
765          5    121.0  72.0  23.0    112.0  26.2     0.245   30         0
766          1    126.0  60.0   NaN      NaN  30.1     0.349   47         1
767          1     93.0  70.0  31.0      NaN  30.4     0.315   23         0

[768 rows x 9 columns]

In [72]:
#Check duplicate file

pima_new.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
763    False
764    False
765    False
766    False
767    False
Length: 768, dtype: bool

In [73]:
import seaborn as sns